#!/usr/bin/env python3
"""Build static sketch instructions and folder READMEs. No dependencies.

Edit sketch-guides.json, then run python3 tools/build-user-docs.py.
Use --check to detect stale generated files without writing them.
"""
import argparse
import html
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE = 'https://mikersays.github.io/agent-arduino/'
REPO = 'https://github.com/mikersays/agent-arduino/blob/main/'
STATUS = ('The repository records compilation with UNO Q core 0.56.0 on the original board. '
          'Typed serial input and most visual behavior still need hardware verification. '
          'These instructions describe the source code, not a new hardware test.')


def build():
    guides = json.loads((ROOT / 'tools/sketch-guides.json').read_text())
    actual = {p.parent.name for p in ROOT.glob('*/*.ino') if p.stem == p.parent.name}
    names = [s['id'] for s in guides]
    if len(names) != len(set(names)) or set(names) != actual:
        raise ValueError('Guide IDs must match every root sketch exactly once')
    esc = html.escape
    sections = []
    outputs = {}
    for s in guides:
        name = s['id']
        ino = f'{name}/{name}.ino'
        source = (ROOT / ino).read_text()
        graphics = 'ArduinoGraphics' in source
        libraries = ('Arduino_RouterBridge and ArduinoGraphics' if graphics else 'Arduino_RouterBridge')
        instructions = [
            'Complete the getting-started guide once to install the UNO Q core and libraries.',
            f'In Arduino IDE, open {ino}. Select Arduino UNO Q and its port.',
            'Click Verify, then Upload. Uploading replaces the running microcontroller sketch.',
        ]
        md = [f'# {name}', '', '<!-- Generated by tools/build-user-docs.py; edit tools/sketch-guides.json. -->', '',
              f"**Level:** {s['level']}. No AI subscription or API key is needed.", '',
              f"[Start here]({SITE}getting-started.html) · [Website instructions]({SITE}sketches.html#{name}) · [All sketches](../README.md)", '',
              '## What you should see', '', s['expected'], '', '## What you need', '', s['hardware'], '',
              f'Install {libraries} with Library Manager. The UNO Q core supplies the board-specific headers.', '',
              '## Upload this sketch', '', *[f'{i}. {step}' for i, step in enumerate(instructions, 1)], '',
              'Or, in the **UNO Q Linux terminal**, from the repository root:', '', '```bash',
              f'python3 flash {name}', '```', '',
              'Read the replacement prompt and enter `y` to compile and upload. To check compilation without uploading:', '',
              '```bash', f'python3 flash {name} --compile-only', '```', '',
              'The helper uploads locally on the board. For a computer-side IDE or network CLI upload, follow the getting-started guide.', '',
              '## Try it', '', s['try_it'], '']
        serial_html = ''
        if s['commands']:
            md += ['## Send commands', '',
                   f'Follow [the serial monitor setup]({SITE}getting-started.html#serial): 115200 baud, newline ending, one command per line. Values in angle brackets describe what to enter; do not type the brackets. A slash separates alternatives.', '',
                   *['- `' + c.split(' — ', 1)[0] + '` — ' + c.split(' — ', 1)[1] for c in s['commands']], '',
                   'Serial input still needs end-to-end verification. Settings are held in memory and reset when the sketch restarts.', '']
            serial_html = ('<h3>Send commands</h3><p>Use <a href="getting-started.html#serial">the serial monitor</a> at 115200 baud with newline endings, one command per line. Replace bracketed values; a slash separates alternatives.</p><ul>' +
                           ''.join('<li>' + esc(c) + '</li>' for c in s['commands']) +
                           '</ul><p>Serial input still needs end-to-end verification. Settings reset when the sketch restarts.</p>')
        else:
            md += ['This sketch has no serial command controls. To change its behavior, edit the source, save, compile, and upload again.', '']
            serial_html = '<p>This sketch has no serial command controls. Change its source and upload again to customize it.</p>'
        if s['notes']:
            md += ['## Limits and tips', '', s['notes'], '']
        md += ['## If it does not work', '',
               f'Compare the result with the expected behavior above, then follow [troubleshooting]({SITE}getting-started.html#troubleshooting). Save your edits before downloading or uploading another version.', '',
               STATUS, '', f'[Read the source]({name}.ino) for the implementation and its original compile/upload commands.', '']
        outputs[ROOT / name / 'README.md'] = '\n'.join(md)
        sections.append(f'''<article id="{name}">
<h2>{name}</h2><p class="small">{esc(s['level'])} · <a href="{REPO}{ino}">Read source</a></p>
<h3>What you should see</h3><p>{esc(s['expected'])}</p>
<h3>What you need</h3><p>{esc(s['hardware'])}</p><p>Library Manager: {libraries}. Board-specific headers come with the UNO Q core.</p>
<h3>Upload</h3><p>Complete <a href="getting-started.html">setup</a> once. In Arduino IDE, open <code>{ino}</code>, select Arduino UNO Q and its port, then Verify → Upload. Uploading replaces the current sketch.</p>
<p>Or run this from the repository root in the <strong>UNO Q Linux terminal</strong>, then confirm with <code>y</code>:</p><pre><code>python3 flash {name}</code></pre>
<p>For a check without uploading: <code>python3 flash {name} --compile-only</code>.</p>
<h3>Try it</h3><p>{esc(s['try_it'])}</p>{serial_html}
{('<h3>Limits and tips</h3><p>' + esc(s['notes']) + '</p>') if s['notes'] else ''}
<p><a href="getting-started.html#troubleshooting">Troubleshooting</a> · <a href="#sketch-index">Back to sketch list</a></p>
</article>''')
    index = ''.join(f'<li><a href="#{s["id"]}">{s["id"]}</a></li>' for s in guides)
    outputs[ROOT / 'docs/sketches.html'] = f'''<!doctype html>
<!-- Generated by tools/build-user-docs.py; edit tools/sketch-guides.json. -->
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Instructions for all {len(guides)} UNO Q sketches</title><meta name="description" content="Upload, wiring, expected behavior, and controls for every UNO Q sketch. No AI subscription required."><link rel="stylesheet" href="assets/guide.css"></head><body>
<a class="skip" href="#main">Skip to instructions</a><nav aria-label="Main navigation"><a href="index.html">Sketch catalog</a><a href="getting-started.html">Getting started</a><a href="sketches.html" aria-current="page">All sketch instructions</a></nav>
<main id="main"><h1>Run any of the {len(guides)} sketches</h1><p>Every sketch is a standalone program you can upload with free Arduino tools. No AI subscription is needed. Begin with <a href="getting-started.html">setup and your first upload</a>, then use these instructions for your next project.</p>
<p>All sketches start without external components. Sensor and signal projects include optional wiring guidance. The four games play themselves with local decision code.</p>
<p class="callout">{STATUS}</p><h2 id="sketch-index">Choose a sketch</h2><ul class="index">{index}</ul>
{''.join(sections)}</main><footer><a href="getting-started.html">Getting started</a> · <a href="index.html">Catalog</a></footer></body></html>
'''
    return outputs


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    stale = []
    for path, content in build().items():
        if path.exists() and path.read_text() == content:
            continue
        stale.append(str(path.relative_to(ROOT)))
        if not args.check:
            path.write_text(content)
    if args.check and stale:
        print('Stale generated files:\n' + '\n'.join(stale))
        return 1
    print(f'{len(stale)} files {"stale" if args.check else "updated"}; all sketch IDs covered.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
